---
title: "Testing_Functions"
output: html_document
---
```{r}
library(tidyverse)
```

#pdxTrees_Parks
```{r}
get_pdxTrees_parks <- function(park = NULL, version = "2017"){
  
  # specify column types
  systems_cols <- readr::cols(
    `Longitude` = readr::col_double(),
    `Latitude` = readr::col_double(),
    `UserID` = readr::col_character(),
    `Genus` = readr::col_character(),
    `Family` = readr::col_character(),
    `DBH` = readr::col_double(), 
    `Inventory_Date` = readr::col_datetime(),
    `Species` = readr::col_character(),
    `Common_Name` = readr::col_character(),
    `Condition` = readr::col_character(),
    `Tree_Height` = readr::col_double(),
    `Crown_Width_NS` = readr::col_double(),
    `Crown_Width_EW` = readr::col_double(),
    `Crown_Base_Height` = readr::col_double(),
    `Collected_By` = readr::col_character(),
    `Park` = readr::col_character(),
    `Scientific_Name` = readr::col_character(),
    `Functional_Type` = readr::col_character(),
    `Mature_Size` = readr::col_factor(),
    `Native` = readr::col_character(),
    `Edible` = readr::col_character(),
    `Nuisance` = readr::col_character(), 
    `Structural_Value` = readr::col_double(), 
    `Carbon_Storage_lb` = readr::col_double(),
    `Carbon_Storage_value` = readr::col_double(),
    `Carbon_Sequestration_lb` = readr::col_double(),
    `Carbon_Sequestration_value` = readr::col_double(),
    `Stormwater_ft` = readr::col_double(),
    `Stormwater_value` = readr::col_double(),
    `Pollution_Removal_value` = readr::col_double(), 
    `Pollution_Removal_oz` = readr::col_double(), 
    `Total_Annual_Services` = readr::col_double(),
    `Origin` = readr::col_character(),
    `Species_Factoid` = readr::col_character()
  ) 
  
  #matching version 
  version <- match.arg(version, choices = c("2017", "2026"))
  
  if (version == 2017) {
  # grabbing the data from github
  dat <- readr::read_csv("https://raw.githubusercontent.com/mcconvil/pdxTrees/master/pdxTrees_parks.csv",
                         col_types = systems_cols)
  # returning the data
  if(is.null(park)){
    return(dat)}
  
  if(!is.null(park)){
    
    # error message if all parks provided are not
    # in dat$Park
    if(sum(park %in% unique(dat$Park)) == 0) { 
      
      stop('Unfortunately the park(s) you listed is(are) not one of the following parks:',
           print(paste(unique(dat$Park), collapse = ", ")))  
    }
    
    
    dat %>%
      dplyr::filter(.data$Park %in% park) %>%
      return()
  } }
  
  if (version == 2026) {
    # grabbing the data from github
    dat <- readr::read_csv("https://github.com/ufds-lab/pdxTrees-project/blob/main/Park_Trees_2026.csv",
                           col_types = systems_cols)
    # returning the data
    if(is.null(park)){
      return(dat)}
    
    if(!is.null(park)){
      
      # error message if all parks provided are not
      # in dat$Park
      if(sum(park %in% unique(dat$Park)) == 0) { 
        
        stop('Unfortunately the park(s) you listed is(are) not one of the following parks:',
             print(paste(unique(dat$Park), collapse = ", ")))  
      }
      
      
      dat %>%
        dplyr::filter(.data$Park %in% park) %>%
        return()
    } } 
}

```

#using pdxTrees_parks
```{r}
get_pdxTrees_parks(park = "Gammans Park", version = "2017")
```


#pdxTrees_Streets
```{r}
get_pdxTrees_streets <- function(neighborhood = NULL, version = "2019"){
  
  
  # specify column types
  systems_cols_2 <- readr::cols(
    "UserID" = readr::col_character(),
    `Inventory_Date` = readr::col_datetime(),
    `Species` = readr::col_character(),
    `DBH` = readr::col_double(),
    `Condition` = readr::col_character(),
    `Site_Type` = readr::col_character(), 
    `Site_Width` = readr::col_double(),
    `Wires` = readr::col_character(),
    `Site_Development` = readr::col_character(),
    `Site_Size` = readr::col_character(),
    `Notes` = readr::col_character(),
    `Address` = readr::col_character(),
    `Neighborhood` = readr::col_character(),
    `Collected_By` = readr::col_character(),
    `Scientific` = readr::col_character(),
    `Family` = readr::col_character(),
    `Genus` = readr::col_character(),
    `Common_Name` = readr::col_character(),
    `Functional_Type` = readr::col_character(),
    `Mature_Size` = readr::col_factor(),
    `Edible` = readr::col_character(),
    `Longitude` = readr::col_double(), 
    `Latitude` = readr::col_double()
  )
  
  #matching version 
  version <- match.arg(version, choices = c("2019", "2026"))
  
  if (version == 2019) {
  # grabbing the data 
  dat_2 <- readr::read_csv("https://raw.githubusercontent.com/mcconvil/pdxTrees/master/pdxTrees_streets.csv",
                           col_types = systems_cols_2)
  
  # returning the data 
  if(is.null(neighborhood)) { return(dat_2) }
  
  if(!is.null(neighborhood)) {
    # error message if all neighborhoods provided are 
    
    # not in dat_2$Neighborhood
    if(sum(neighborhood %in% unique(dat_2$Neighborhood)) == 0) { 
      
      stop('Unfortunately the park you listed is not one of the following Neighborhoods:', 
           print(paste(unique(dat_2$Neighborhood), collapse = ", ")))
    }
    
    dat_2 %>%
      dplyr::filter(.data$Neighborhood %in% neighborhood) %>%
      return()} }
  if (version == 2026) {
    dat_2 <- readr::read_csv("https://github.com/ufds-lab/pdxTrees-project/blob/main/Street_Trees_2026.csv",
                             col_types = systems_cols_2)
    
    # returning the data 
    if(is.null(neighborhood)) { return(dat_2) }
    
    if(!is.null(neighborhood)) {
      # error message if all neighborhoods provided are 
      
      # not in dat_2$Neighborhood
      if(sum(neighborhood %in% unique(dat_2$Neighborhood)) == 0) { 
        
        stop('Unfortunately the park you listed is not one of the following Neighborhoods:', 
             print(paste(unique(dat_2$Neighborhood), collapse = ", ")))
      }
      
      dat_2 %>%
        dplyr::filter(.data$Neighborhood %in% neighborhood) %>%
        return()} 
}}
```

```{r}

get_pdxTrees_parks()

```

